# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-03 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesstruc',
            name='FotBayNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vesstruc',
            name='TweBayNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vesstruc',
            name='VesFrLeng',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vesstruc',
            name='VesLeng',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vesstruc',
            name='VesType',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vesstruc',
            name='VesWidth',
            field=models.IntegerField(null=True),
        ),
    ]
