# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190403_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesstruc',
            name='DanCtnAlw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vesstruc',
            name='MidBayDeaWit',
            field=models.BooleanField(default=False),
        ),
    ]
