# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190403_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesbaystruc',
            name='BayCom',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vesbaystruc',
            name='BaySiz',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vesbaystruc',
            name='VesType',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vesstruc',
            name='EngRomWid',
            field=models.IntegerField(default=60, null=True),
        ),
    ]
