# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190404_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vesstruc',
            old_name='CabCap',
            new_name='CabHeg',
        ),
        migrations.RenameField(
            model_name='vesstruc',
            old_name='DeckCapWegt',
            new_name='CabWidMax',
        ),
        migrations.RenameField(
            model_name='vesstruc',
            old_name='LoadWeigth',
            new_name='DeckHeg',
        ),
        migrations.RemoveField(
            model_name='vesbaystruc',
            name='VesType',
        ),
        migrations.RemoveField(
            model_name='vesbaystruc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='CapCtnFotFiv',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='DanCtnAlw',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='HigCtnCap',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='MidBayDeaWit',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='RefCtnCap',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='VesAtt',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='VesBerSpd',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='VesEmpGrvHeg',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='VesEntBerSpd',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='VesType',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='id',
        ),
        migrations.AddField(
            model_name='vesbaystruc',
            name='VesName',
            field=models.CharField(default='SMU01', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vesstruc',
            name='DeckWidMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vesstruc',
            name='VesName',
            field=models.CharField(default='SMU01', max_length=6, primary_key=True, serialize=False),
        ),
    ]
