# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190410_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BayStruc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VesName', models.CharField(max_length=12)),
                ('BayNo', models.CharField(max_length=6)),
                ('BaySiz', models.CharField(max_length=6, null=True)),
                ('BayCom', models.CharField(max_length=6, null=True)),
                ('DeckHeg', models.IntegerField(null=True)),
                ('DeckWidMax', models.IntegerField(null=True)),
                ('CabHeg', models.IntegerField(null=True)),
                ('CabWidMax', models.IntegerField(null=True)),
                ('HatCovKind', models.CharField(max_length=6, null=True)),
                ('HatCovSiz', models.IntegerField(null=True)),
                ('BayX', models.IntegerField(null=True)),
                ('BayY', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VesBayStruc',
        ),
        migrations.RemoveField(
            model_name='vesstruc',
            name='VesFrLeng',
        ),
        migrations.AlterUniqueTogether(
            name='baystruc',
            unique_together=set([('VesName', 'BayNo')]),
        ),
    ]
