# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_bayinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baystruc',
            name='HatCovKind',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
